name: "Benchmarks"

on: workflow_dispatch

jobs:
  benchmarks:
    name: Benchmarks
    runs-on: ubuntu-latest
    steps:
    - name: Repository Checkout
      uses: actions/checkout@v3
    - name: .NET Setup
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          2.1.x
          3.1.x
          5.0.x
          6.0.x
    - name: Restore
      working-directory: Solution/
      run: dotnet restore --force-evaluate
    - name: Build
      working-directory: Solution/
      run: dotnet build --verbosity normal --configuration Release --no-restore --no-incremental
    - name: Run
      working-directory: Solution/
      run: dotnet run --project FastHashes.Benchmarks/FastHashes.Benchmarks.csproj --framework netcoreapp3.1 --verbosity normal --configuration Release --no-restore --no-build
 
