name: "Benchmarks"

on: workflow_dispatch

jobs:
  benchmarks:
    name: Benchmarks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dotnet-version: [ 2.1.x, 3.1.x ]
    steps:
    - name: Repository Checkout
      uses: actions/checkout@v2
    - name: .NET Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore
      working-directory: Solution/
      run: dotnet restore --force-evaluate
    - name: Build
      working-directory: Solution/
      run: dotnet build FastHashes.sln --configuration Release --no-restore --no-incremental --verbosity normal
    - name: Run
      working-directory: Solution/
      run: dotnet run --project FastHashes.Benchmarks/FastHashes.Benchmarks.csproj --configuration Release --no-restore --no-build --verbosity normal
