name: "Continuous Integration"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  continuous_integration:
    name: Continuous Integration
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
    - name: Repository Checkout
      uses: actions/checkout@v2
    - name: .NET Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          2.1.x
          3.1.x
          5.0.x
          6.0.x
    - name: Restore
      working-directory: Solution/
      run: dotnet restore --force-evaluate
    - name: Build
      working-directory: Solution/
      run: dotnet build --verbosity normal --configuration Release --no-restore --no-incremental
    - name: Test
      working-directory: Solution/
      run: dotnet test --verbosity normal --configuration Release --no-restore --no-build --collect "XPlat Code Coverage" --settings Coverage.runsettings --results-directory Coverage
    - name: Run script file
      run: |
        pwd
      shell: bash
    - name: Coverage Report Creation
      uses: danielpalme/ReportGenerator-GitHub-Action@5.1.9
      with:
        reports: 'Coverage/*/coverage.info'
        reporttypes: 'lcov'
        targetdir: 'Coverage'
        verbosity: 'Info'
    - name: Coverage
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: Solution/Coverage/coverage.info
