name: "Continuous Integration"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  COVERLET_ENABLETRACKERLOG: 1

jobs:
  continuous_integration:
    name: Continuous Integration
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
    - name: Repository Checkout
      uses: actions/checkout@v3
    - name: .NET Setup
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          2.1.x
          3.1.x
          5.0.x
          6.0.x
    - name: Restore
      working-directory: Solution/
      run: dotnet restore --force-evaluate
    - name: Build
      working-directory: Solution/
      run: dotnet build --verbosity normal --configuration Release --no-restore --no-incremental
    - name: Test
      working-directory: Solution/
      run: dotnet test --verbosity normal --configuration Release --no-restore --no-build --collect "XPlat Code Coverage" --settings Coverage.runsettings --diag Coverage/log.txt --results-directory Coverage/
    - name: Coverage Report Creation
      uses: danielpalme/ReportGenerator-GitHub-Action@5.1.9
      with:
        reports: 'Solution/Coverage/*/coverage.info'
        reporttypes: 'lcov'
        targetdir: 'Solution/Coverage/'
        verbosity: 'Info'
    - name: Coverage Report Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Coverage Artifact (${{ matrix.os }})
        path: Solution/Coverage/
    - name: Coverage Report Upload
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: Solution/Coverage/lcov.info
