name: "Continuous Integration"

#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
on: [ workflow_dispatch ]

jobs:
  continuous_integration:
    name: Continuous Integration
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        dotnet-version: [ 2.x, 3.x, 5.x ]
    steps:
    - name: Repository Checkout
      uses: actions/checkout@v2
    - name: .NET Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore Dependencies
      run: dotnet restore 
      working-directory: ./Solution
    - name: Build
      run: |
        dotnet build ./FastHashes/FastHashes.csproj --configuration Release --no-restore --nologo --verbosity normal
        dotnet build ./FastHashes.Tests/FastHashes.Tests.csproj --configuration Release --no-restore --nologo --verbosity normal
      working-directory: ./Solution
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
      working-directory: ./Solution
