name: "Continuous Integration"

#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
on: [ workflow_dispatch ]

jobs:
  continuous_integration:
    name: Continuous Integration
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        dotnet-version: [ 2.1.x ]
    steps:
    - name: Repository Checkout
      uses: actions/checkout@v2
    - name: .NET Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore Dependencies
      run: dotnet restore --force-evaluate
      working-directory: ./Solution
    - name: Build
      run: dotnet build ./FastHashes.sln --configuration Release --no-restore --no-incremental --verbosity normal
      working-directory: ./Solution
    - name: Test
      run: dotnet test ./FastHashes.sln --configuration Release --no-restore --no-build --logger "console;verbosity=normal" --verbosity normal
      working-directory: ./Solution
