name: "Endianness Tests"

on: workflow_dispatch

jobs:
  big_endian:
    name: Big Endian
    runs-on: ubuntu-latest
    steps:
    - name: Multiarch Setup
      run: |
        docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - name: Tests
      uses: docker://multiarch/ubuntu-core:s390x-focal
      with:
        args: >
          bash -c
          "
            uname -a &&
            apt-get update -y &&
            apt-get install -y git python3 &&
            git clone https://github.com/TommasoBelluzzo/FastHashes &&
            python3 FastHashes/FastHashes/Solution/FastHashes.Tests/endianness_tests.py
          "
  little_endian:
    name: Little Endian
    runs-on: ubuntu-latest
    steps:
    - name: Tests
      run: |
        apt-get update
        apt-get install -y git python3
        git clone https://github.com/TommasoBelluzzo/FastHashes
        python3 FastHashes/FastHashes/Solution/FastHashes.Tests/endianness_tests.py