name: License Update

on:
  schedule:
    - cron: '05 00 1 1 *'

jobs:
  task:
    name: Task
    runs-on: ubuntu-latest
    steps:
    - name: Repository Checkout
      uses: actions/checkout@v3
    - name: Year Replacement
      env:
        LICENSE_REGEX: 2017-\d{4}
      run: |
        CURRENT_YEAR=$(date +%Y)
        FILES=0
        while IFS= read -r FILE; do
          PATTERN=$(grep -Poh "$LICENSE_REGEX" "$FILE")
          sed -i "s/$PATTERN/2017-$CURRENT_YEAR/g" "$FILE"
          grep -P "$LICENSE_REGEX" "$FILE"
          FILES=$((FILES+1))
        done < <(grep -P "$LICENSE_REGEX" -Rl .)
        if [[ "$FILES" -ne 2 ]]; then
          echo "NO FILES CHANGED"
          exit 1
        fi
        git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git config --local user.name "${{ secrets.BOT_USERNAME }}"
        git config --local user.email "${{ secrets.BOT_EMAIL }}"
        git add --a
        git diff-index --quiet HEAD || git commit -m "License $CURRENT_YEAR"
        git push
