name: "Multiarch"

on: workflow_dispatch

jobs:
  multiarch:
    runs-on: ubuntu-20.04
    name: Commands
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2
        name: Commands
        id: runcmd
        with:
          arch: s390x
          distro: ubuntu20.04
          run: |
            uname -a
            lscpu | grep Endian
            apt-get update
            apt-get install -y wget
            wget -q https://dot.net/v1/dotnet-install.sh &&
            chmod +x dotnet-install.sh &&
            ./dotnet-install.sh -c 6.0 &&
            dotnet --version &&
            git clone https://github.com/TommasoBelluzzo/FastHashes &&
            cd FastHashes/Solution/ &&
            dotnet restore --force-evaluate &&
            dotnet build --verbosity normal --configuration Release --no-restore --no-incremental &&
            dotnet test --verbosity normal --configuration Release --no-restore --no-build
