name: "Multiarch"

on: workflow_dispatch

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
    - name: Multiarch Setup
      run: |
        docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - name: Multiarch Tests
      uses: docker://multiarch/ubuntu-core:s390x-focal
      with:
        args: >
          bash -c
          "uname -a &&
          lscpu | grep Endian &&
          apt-get update &&
          apt list dotnet &&
          apt-get install -y wget &&
          apt-get install -y apt-transport-https &&
          wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb &&
          dpkg -i packages-microsoft-prod.deb &&
          apt-get update &&
          apt-get install -y dotnet-sdk-3.1 &&
          dotnet --version &&
          git clone https://github.com/TommasoBelluzzo/FastHashes &&
          cd FastHashes/Solution/ &&
          dotnet restore --force-evaluate &&
          dotnet build --verbosity normal --configuration Release --no-restore --no-incremental &&
          dotnet test --verbosity normal --configuration Release --no-restore --no-build
          "
