name: Package Publishing

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target:'
        required: true
        default: 'MINOR'

jobs:
  task:
    name: Task
    runs-on: ubuntu-latest
    steps:
    - name: Repository Checkout
      uses: actions/checkout@v2
    - name: .NET Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
    - name: Version Bump
      id: bump
      env:
        TARGET: ${{ github.event.inputs.target }}
        VERSION_REGEX: Version>\d+\.\d+\.\d+
        VERSION_FILE: Solution/Directory.Build.props
      run: |
        TARGET="${TARGET^^}"
        if [[ "$TARGET" != "MAJOR" ]] && [[ "$TARGET" != "MINOR" ]] && [[ "$TARGET" != "BUILD" ]]; then
          echo "INVALID INPUT"
          exit 1
        fi
        grep -P "<$VERSION_REGEX" "$VERSION_FILE"
        VERSION=$(grep -P "<$VERSION_REGEX" "$VERSION_FILE" | cut -d ">" -f2)
        VERSION_MAJOR=$(echo "$VERSION" | cut -d "." -f1)
        VERSION_MINOR=$(echo "$VERSION" | cut -d "." -f2)
        VERSION_BUILD=$(echo "$VERSION" | cut -d "." -f3)
        if [[ "$TARGET" == "MAJOR" ]]; then
          VERSION_MAJOR=$(($VERSION_MAJOR+1))
          VERSION_MINOR=0
          VERSION_BUILD=0
        elif [[ "$TARGET" == "MINOR" ]]; then
          VERSION_MINOR=$(($VERSION_MINOR+1))
          VERSION_BUILD=0
        else
          VERSION_BUILD=$(($VERSION_BUILD+1))
        fi
        exit 1
        VERSION=$(printf "%d.%d.%d" $VERSION_MAJOR $VERSION_MINOR $VERSION_BUILD 2>/dev/null)
        ASSEMBLY_VERSION=$(printf "%d.0.0" $VERSION_MAJOR 2>/dev/null)
        PATTERN=$(grep -Poh "<$VERSION_REGEX" "$VERSION_FILE")
        sed -i "s/$PATTERN/<Version>$VERSION/g" "$VERSION_FILE"
        grep -P "<$VERSION_REGEX" "$VERSION_FILE"
        PATTERN=$(grep -Poh "<File$VERSION_REGEX" "$VERSION_FILE")
        sed -i "s/$PATTERN/<FileVersion>$VERSION/g" "$VERSION_FILE"
        grep -P "<File$VERSION_REGEX" "$VERSION_FILE"
        if [[ "$TARGET" == "MAJOR" ]]; then
          PATTERN=$(grep -Poh "<Assembly$VERSION_REGEX" "$VERSION_FILE")
          sed -i "s/$PATTERN/<AssemblyVersion>$ASSEMBLY_VERSION/g" "$VERSION_FILE"
          grep -P "<Assembly$VERSION_REGEX" "$VERSION_FILE"
        fi
        echo "::set-output name=version::$VERSION"
    - name: Restore
      working-directory: Solution/
      run: dotnet restore --force-evaluate
    - name: Build
      working-directory: Solution/
      run: dotnet build FastHashes/FastHashes.csproj --configuration Release --no-restore --no-incremental --verbosity normal
    - name: Pack
      working-directory: Solution/
      run: dotnet pack FastHashes/FastHashes.csproj --output ../Package/ --configuration Release --no-restore --no-build --include-symbols --verbosity normal
    - name: Publish
      env:
        VERSION: ${{ steps.bump.outputs.version }}
      working-directory: Solution/
      run: dotnet nuget push Package/FastHashes.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_TOKEN }}
    - name: Version Commit
      env:
        VERSION: ${{ steps.bump.outputs.version }}
      run: |
        git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git config --local user.name "${{ secrets.BOT_USERNAME }}"
        git config --local user.email "${{ secrets.BOT_EMAIL }}"
        git add --a
        git commit -m "Release $VERSION"  
        git push
