name: Package Publishing

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target:'
        required: true
        default: 'MINOR'

jobs:
  task:
    name: Task
    runs-on: ubuntu-latest
    steps:
    - name: Repository Checkout
      uses: actions/checkout@v3
    - name: .NET Setup
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          2.1.x
          3.1.x
          5.0.x
          6.0.x
    - name: Version Bump
      id: bump
      env:
        TARGET: ${{ github.event.inputs.target }}
        VERSION_REGEX: Version>\d+\.\d+\.\d+
        VERSION_FILE: Solution/Directory.Build.props
      run: |
        TARGET="${TARGET^^}"
        if [[ "$TARGET" != "MAJOR" ]] && [[ "$TARGET" != "MINOR" ]] && [[ "$TARGET" != "BUILD" ]]; then
          echo "INVALID INPUT"
          exit 1
        fi
        grep -P "<$VERSION_REGEX" "$VERSION_FILE"
        VERSION=$(grep -P "<$VERSION_REGEX" "$VERSION_FILE" | cut -d ">" -f2)
        VERSION_MAJOR=$(echo "$VERSION" | cut -d "." -f1)
        VERSION_MINOR=$(echo "$VERSION" | cut -d "." -f2)
        VERSION_BUILD=$(echo "$VERSION" | cut -d "." -f3)
        if [[ "$TARGET" == "MAJOR" ]]; then
          VERSION_MAJOR=$(($VERSION_MAJOR+1))
          VERSION_MINOR=0
          VERSION_BUILD=0
        elif [[ "$TARGET" == "MINOR" ]]; then
          VERSION_MINOR=$(($VERSION_MINOR+1))
          VERSION_BUILD=0
        else
          VERSION_BUILD=$(($VERSION_BUILD+1))
        fi
        VERSION=$(printf "%d.%d.%d" $VERSION_MAJOR $VERSION_MINOR $VERSION_BUILD 2>/dev/null)
        ASSEMBLY_VERSION=$(printf "%d.0.0" $VERSION_MAJOR 2>/dev/null)
        PATTERN=$(grep -Poh "<$VERSION_REGEX" "$VERSION_FILE")
        sed -i "s/$PATTERN/<Version>$VERSION/g" "$VERSION_FILE"
        grep -P "<$VERSION_REGEX" "$VERSION_FILE"
        PATTERN=$(grep -Poh "<File$VERSION_REGEX" "$VERSION_FILE")
        sed -i "s/$PATTERN/<FileVersion>$VERSION/g" "$VERSION_FILE"
        grep -P "<File$VERSION_REGEX" "$VERSION_FILE"
        if [[ "$TARGET" == "MAJOR" ]]; then
          PATTERN=$(grep -Poh "<Assembly$VERSION_REGEX" "$VERSION_FILE")
          sed -i "s/$PATTERN/<AssemblyVersion>$ASSEMBLY_VERSION/g" "$VERSION_FILE"
          grep -P "<Assembly$VERSION_REGEX" "$VERSION_FILE"
        fi
        echo "::set-output name=version::$VERSION"
    - name: Readme Formatting Pre
      run: |
        sed -e $'/<table>/,/<\/table>/d' README.md | sed 's/\r$//' | tr '\n' '~' | sed 's/\~\~\~/\~\~/' | tr '~' '\n' > README.md
        cat README.md
    - name: Restore
      working-directory: Solution/
      run: dotnet restore --force-evaluate
    - name: Build
      working-directory: Solution/
      run: dotnet build --verbosity normal --configuration Release --no-restore --no-incremental /p:DeterministicSourcePaths=true
    - name: Pack
      working-directory: Solution/
      run: dotnet pack FastHashes/FastHashes.csproj --verbosity normal --configuration Release --no-restore --no-build --output ../Package/
    - name: Package Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Package Artifact
        path: Package/

